[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "AdnyC21rlD"
weight = 9_999

[[main]]
name = "Archives"
pageRef = "archives"
identifier = "djcNKZgBGH"
weight = 9_999

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "PgP6Ou7IlC"
weight = 9_999

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "hmFmXE0PKV"
weight = 9_999

[[footer]]
none = "none"
